### ISSUE TITLE
How long for import data step?

### ISSUE THREAD

**Issue by kirkins** [PhaedrusTheGreek/nhl-stats-elasticsearch#1]
I'm completely new to elasticsearch. I'm currently following the instructions and feel like the import step is taking forever. Is that normal or is there likely a problem?

![screenshot_2017-02-21_09-00-47](https://cloud.githubusercontent.com/assets/9503662/23167912/41649160-f814-11e6-9e15-84fba8416ab4.png)

**Comment by PhaedrusTheGreek** [comment]
That's probably normal - it might take 30 minutes or even longer to download an entire season, depending on your internet connection speed.

**Comment by kirkins** [comment]
Ah makes sense. One more thing. 

Running locally now and it seems like it needs a lot of resources. Do you think elasticsearch would run ok on an EC2 t2.micro instance?

**Comment by PhaedrusTheGreek** [comment]
You could probably make it work, but you would have to [tune down the amount of memory](https://www.elastic.co/guide/en/elasticsearch/reference/master/heap-size.html) ES uses to only 500-700mb or so - you'd only be able to put limited pressure on the node with limited resources.
